## Basic Configuration
baseurl = "https://ky-kimeng.netlify.com/"
languageCode = "en"

title = "Kim Eng KY"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Kim Eng KY"
    themeColor = "theme-base-0c"
    # title = "Title"
    description = "\"It is a capital mistake to theorize before one has data.\" - Sherlock Holmes"
    authorimage = "/img/ky-headshot.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "kykimeng"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "kykimeng"
    twitter = "kimmyky2"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    email = "kykimeng@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 300
    url = "/pdf/ky-resume.pdf"
