theme = "hyde"
baseURL = "http://kykimeng.github.io/"
languageCode = "en-us"
title = "Kim Eng KY"

[params]
  themeColor = "theme-base-0c"
  name = "Kim Eng KY"
  description = "\"It is a capital mistake to theorize before one has data.\" - Sherlock Holmes"