theme = "hyde"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kim Eng KY"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  themeColor = "theme-base-0c"
  name = "Kim Eng KY"
  description = "\"It is a capital mistake to theorize before one has data.\" - Sherlock Holmes"